version: '3'
services:
  mysql:
    container_name: mysql-config
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=nacos_config
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3300:3306
    volumes:
      - ./data/mysql-config:/var/lib/mysql
  nacos:
    image: nacos/nacos-server:v2.3.0
    depends_on:
      - mysql
    container_name: nacos-GopherTok
    env_file:
      - ./nacos-standlone-mysql.env
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ./data/nacos:/home/nacos/data
    restart: always
