version: "3"

services:
  mysql:
    container_name: pmail-mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=pmail
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - "./data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysql", "pmail", "-uroot", "-proot", "-e", "select 1"]
      interval: 5s
      timeout: 10s
      retries: 30
  pmail:
    container_name: pmail
    image: 'ghcr.io/jinnrry/pmail:latest'
    volumes:
      - './config:/work/config'
    ports:
      - '465:465'
      - '8781:443'
      - '8780:80'
      - '25:25'