version: '3'
services:
  etcd-single:
    image: quay.io/coreos/etcd:v3.5.12
    restart: on-failure
    entrypoint: ["/usr/local/bin/etcd", "--config-file", "/tmp/etcd/single/conf/etcd.yml"]
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      ETCDCTL_API: 3
    volumes:
      - ./etcd.yml:/tmp/etcd/single/conf/etcd.yml
