version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysql", "test", "-uroot", "-proot", "-e", "select 1"]
      interval: 5s
      timeout: 10s
      retries: 30
